### ISSUE TITLE
create new section to add technical session 

### ISSUE THREAD

**Issue by mohamedsayed1994** [amateursanonymous/amateursanonymous.github.io#39]
update meetings page to create new section for add technical session 
 main link as it is. 
content two links for soft and technical then in each link content the past meetings and the next meeting date.

**Comment by MGamalE** [comment]
@MohamedRadwan-DevOps I'll work on this issue! Could you assign it to me ?

**Comment by mohamedsayed1994** [comment]
issue canceled will not add technical session on the site
